name = "aiken-lang/sample"
version = "main"
compiler = "v1.1.12"
plutus = "v3"
license = "Apache-2.0"
description = "A library for writing Aiken's samplers."

[repository]
user = "aiken-lang"
project = "sample"
platform = "github"

[[dependencies]]
name = "aiken-lang/stdlib"
version = "v2"
source = "github"

[config]
