name: Continuous Integration

on:
  push:
    branches: ["main"]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: cargo install --verbose --git https://github.com/aiken-lang/aiken.git
      - run: aiken fmt --check
      - run: aiken check -D
      - run: aiken build
